### ISSUE TITLE
knoxnl does not save remaining URLs in .todo file

### ISSUE THREAD

**Issue by Nishantbhagat57** [xnl-h4ck3r/knoxnl#19] opened 2024-04-29 09:26 UTC
knoxnl is no longer saving remaining URLs in the .todo file as it used to.
knoxnl version 4.2 (latest)

knoxnl command I used:
```
knoxnl --input /home/nishant57/urls.txt --retries 50000 --api-key 'xxxxxx-xxxxxx-xxxxxx-xxxxx-xxxxxxx' --timeout 2500 --advanced-filter-bypass --output /home/nishant57/knoxss_result.txt
```

The .todo remaining URLs file is saved when I kill knoxnl using Ctrl+C but not when knoxnl is stopped in between due to errors.

![Screenshot 2024-04-29 143805](https://github.com/xnl-h4ck3r/knoxnl/assets/64642374/ed948624-4988-49c6-8a95-6bfecbb3ef95)

**Comment by xnl-h4ck3r** [comment] 2024-04-29 17:23
Hi @Nishantbhagat57, thanks for raising this! I hadn't noticed that. I am working on a number of changes to knoxnl at the moment, so I will get this sorted too and try to release as soon as I can. Sorry for the problem

**Comment by xnl-h4ck3r** [comment] 2024-04-29 22:08
Hi @Nishantbhagat57 

One point I would make is that if you set the number of retries so high, you should really change the `-rb`/`--retry-backoff` to `1` so it doesn't increase so much. It defaults to `1.5` which means the first wait is 30 seconds (the default), the next 45 seconds, next 90 seconds, etc. So if it actually got to 50,000 retry it would be, according to chatGPT would be "This is an astronomically large number! To put it in perspective, it's far greater than the age of the universe in seconds." 😂
Apologies if that wasn't clear from the documentation. So if you set `-rb 1` then it will just wait 30 seconds every time.

So when you ran with the command you gave, you said "knoxnl is stopped in between due to errors."... what error did it actually stop with? Did it actually complete, or did it just wait and get killed for some other reason? I have tried reproducing this but I always get the `.todo` file so I'm not 100% sure what is happening. Can you try using the `-v` option and see if there any more useful messages from that?

Thanks

**Comment by Nishantbhagat57** [comment] 2024-04-30 09:17
Hii @xnl-h4ck3r, thank you for your response.

Haha, you're right, I should have checked the `--retry-backoff`. At that time, my thought process was "90% of the time it's the KNOXSS API that gives error. Let's set `--retries` to 50000. I don't want to stop if the current request is giving an error; it might work on the next request. And after all, I am paying for this service." Let's be honest, I think the 5000 req/day limit is a joke. It can only process 1000 req/day at max. Even after having multiple chats with the KNOXSS creator, he still hasn't improved the infrastructure. Anyway, thanks for pointing this out. I will try with `-rb 1` and let you know the result.

> So when you ran with the command you gave, you said "knoxnl is stopped in between due to errors."... what error did it actually stop with? Did it actually complete, or did it just wait and get killed for some other reason? I have tried reproducing this but I always get the `.todo` file so I'm not 100% sure what is happening. Can you try using the `-v` option and see if there any more useful messages from that?
>

No, the file had around 1k URLs, and it stopped at 525 due to some errors. I'll try again with `-rb 1 --retries 50000`, which I think will resolve the issue.

Once again, thank you for your prompt response :)

Regards,
Nishant

**Comment by xnl-h4ck3r** [comment] 2024-04-30 10:55
No problem! I'm not too sure if this will actually resolve the issue you had though, but let me know

**Comment by Nishantbhagat57** [comment] 2024-05-01 09:03
Hii @xnl-h4ck3r
#### So, I ran the test, and here are the results:

I had 1045 URLs in the input.txt file.
API calls made - 521/5000

The total number of API calls made is the same as in the last test. Previously, I assumed it had only scanned 521 URLs, and the remaining URLs weren't saved in the .todo file.

#### But upon revisiting this, I realized:
Only 521 of the URLs were successfully scanned by the KNOXSS API, and the rest got rejected. This means 524 URLs (1045-521) were rejected by KNOXSS and would be rejected again regardless. 

So, knoxnl did its job; it passed all the URLs to KNOXSS, meaning no URLs remained to be scanned. That's probably why it didn't save the .todo file - because there were no remaining URLs.

I think knoxnl should provide statistics about how many URLs it processed and how many are remaining when the scan completes or gets killed.

![Screenshot 2024-05-01 141512](https://github.com/xnl-h4ck3r/knoxnl/assets/64642374/12ab6397-db6f-47eb-af8c-4995f8e49f25)

**Comment by xnl-h4ck3r** [comment] 2024-05-01 15:10
Hi @Nishantbhagat57. It's good to hear it's mostly doing it's job. I'll add to the TODO list to add some more stats to the end. There's quite a few changes coming very soon, so I'll try to get that added with those changes. I'll close this issue though as the main problem has been resolved. Thanks

**Closed by xnl-h4ck3r** 2024-05-01 15:10 UTC
Labels: bug
