### ISSUE TITLE
-pur parameter with bug

### ISSUE THREAD

**Issue by j0hnZ3RA** [xnl-h4ck3r/knoxnl#21] opened 2024-05-02 12:32 UTC
First of all congratulations on the latest update, it has brought great features to the tool. However, yesterday I went to use the -pur parameter and realized that at a certain moment I received an error for exceeding the rate limit and it enabled the -pur option, which doesn't make sense, rate limit it would just have to wait a little longer maybe, a few seconds so as not to overload the API and then come back again, but it understood that my number of calls had exceeded.

![Captura de tela 2024-05-02 092348](https://github.com/xnl-h4ck3r/knoxnl/assets/82909572/db37b4ba-c7d0-4634-adc2-0a5bef938304)

**Comment by xnl-h4ck3r** [comment] 2024-05-02 12:57
Hi @j0hnZ3RA. Apologies, that is a huge bug that I caused by leaving some test code in :/
Please run `pip install --upgrade knoxnl` now and that should be fixed. Sorry!

**Comment by j0hnZ3RA** [comment] 2024-05-02 15:02
No problem, it happens sometimes 😊, thanks!

**Closed** 2024-05-14 22:53 UTC
